kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mio-cluster

nodes:
  - role: control-plane  # Nodo master
    image: kindest/node:v1.32.0
    labels:
      custom-label: "control-plane"
    extraPortMappings:
      - containerPort: 2424   # Per il kube-controller-manager
        hostPort: 2424
        protocol: TCP
  
  - role: worker  # Nodo worker
    image: kindest/node:v1.32.0  
    labels:
      custom-label: "worker"
    extraPortMappings:
      - containerPort: 2525
        hostPort: 2525
        protocol: TCP
      

