apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJtYXJzaWxlbmNlIiwicGFzc3dvcmQiOiJXaGl0ZXNpbGVuY2UyNiIsImVtYWlsIjoidW5pMzgwOTE4QHN0dWRpdW0udW5pY3QuaXQiLCJhdXRoIjoiYldGeWMybHNaVzVqWlRwWGFHbDBaWE5wYkdWdVkyVXlOZz09In19fQ==
kind: Secret
metadata:
  name: my-registry-secret
  namespace: my-app
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials-secret
  namespace: my-app
type: Opaque
data:
  DB_HOST: bXlzcWw=         
  DB_NAME: bXlfZGI=         
  DB_PASSWORD: bXlfcGFzcw== 
  DB_USER: bXlfdXNlcg==    
  
---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-access-config-secret
  namespace: my-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=  
  MYSQL_DATABASE: bXlfZGI=           
  MYSQL_USER: bXlfdXNlcg==           
  MYSQL_PASSWORD: bXlfcGFzcw==       
---

apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: my-app
type: Opaque
data:
  SMTP_PASSWORD: eXRndSB4am11IHV4YnAgZXp2dg==
  SMTP_USER: YWxlcnQuc3lzdGVtMjZAZ21haWwuY29t


